### ISSUE TITLE
Idea: Logging of delay between two keys

### ISSUE THREAD

**Issue by moritz-ferdinand-rocker** [Dimagog/ErgoTapCraft#1]
Instead of guessing, which finger is how fast, it would be very interesting to know, what's the (mean) delay between two keys - including the same key twice.

**Comment by Dimagog** [comment]
`-f human` prints delay since the last key event.

However I have found it almost useless: there is too much magic happening inside the keyboard with mod-taps, layer-taps, and tap-dances. So the actual time of physical key presses/releases is very loosely correlated with when the OS sees them. They come to OS with significant and unpredictable delays.

If you want the real timing info on when your fingers actually pressing/releasing keys the best course of action would be to modify your QMK config: enable Console, add `xprintf` to `process_record_user`, and use `hid_listen.exe` to see the console output.
